# Site settings
title:          DAWON
description:    "Welcome to Dawon's work, I love figuring out how people think & react. Marketing."
url:            https://github.com/inelaah/rain

# Author
author:
  name:         Dawon Ko
  email:        dawonkouk@gmail.com
  url:          https://dawonko.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: dawonkouk@gmail.com
  github: https://github.com/dawonko
  twitter: https://twitter.com
  linkedin: https://ba.linkedin.com/
